name: aws deployment
on:
  push
jobs:
  deploy_resource:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code.
        uses: actions/checkout@v4
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::353075014684:role/Genpact-POC-PowerUser
          aws-region: us-east-1
      - name: terraform format check
        id: fmt
        run: terraform fmt
      - name: terraform init
        id: id
        run: terraform init
      - name: terraform plan
        id: plan
        run: terraform plan -input=false
        continue-on-error: true
      - name: terraform apply
        id: apply
        run: terraform apply -auto-approve
      
    